=== DXYyang/SDP/sourcedata/poi-REL_2_5_1/src/documentation/content/xdocs/dtd/changes-v11.dtd
<!-- ===================================================================

     Apache Changes DTD (Version 1.1)

PURPOSE:
  This DTD was developed to create a simple yet powerful document
  type for software development changes for use with the Apache projects.
  It is an XML-compliant DTD and it's maintained by the Apache XML
  project.

TYPICAL INVOCATION:

  <!DOCTYPE document PUBLIC
       "-//APACHE//DTD Changes Vx.y//EN"
       "changes-vxy.dtd">

  where

    x := major version
    y := minor version

NOTES:
  It is important, expecially in open developped software projects, to keep
  track of software changes both to give users indications of bugs that might
  have been resolved, as well, and not less important, to provide credits
  for the support given to the project. It is considered vital to provide
  adequate payback using recognition and credits to let users and developers
  feel part of the community, thus increasing development power.

AUTHORS:
  Stefano Mazzocchi <stefano@apache.org>

FIXME:

CHANGE HISTORY:
[Version 1.0]
  19991129 Initial version. (SM)
  20000316 Added bugfixing attribute. (SM)
[Version 1.1]
  20011212 Used public identifiers for external entities (SM)
  
COPYRIGHT:
  Copyright (c) @year@ The Apache Software Foundation.

  Permission to copy in any form is granted provided this notice is
  included in all copies. Permission to redistribute is granted
  provided this file is distributed untouched in all its parts and
  included files.

==================================================================== -->

<!-- =============================================================== -->
<!-- Include the Documentation DTD -->
<!-- =============================================================== -->

<!ENTITY % document PUBLIC
    "-//APACHE//DTD Documentation V1.1//EN"
    "document-v11.dtd">
%document;

<!-- =============================================================== -->
<!-- Common entities -->
<!-- =============================================================== -->

<!ENTITY % types "add|remove|update|fix">

<!-- =============================================================== -->
<!-- Document Type Definition -->
<!-- =============================================================== -->

<!ELEMENT changes (devs, release*)>
<!ATTLIST changes %common.att;
                  %title.att;>

    <!ELEMENT devs (person+)>
    <!ATTLIST devs %common.att;>

    <!ELEMENT release (action+)>
    <!ATTLIST release %common.att;
                      version  CDATA  #REQUIRED
                      date     CDATA  #REQUIRED>

        <!ELEMENT action (%content.mix;)*>
        <!ATTLIST action %common.att;
                         dev  IDREF  #REQUIRED
                         type (%types;)  #IMPLIED
                         due-to CDATA #IMPLIED
                         due-to-email CDATA #IMPLIED
                         fixes-bug CDATA #IMPLIED>

<!-- =============================================================== -->
<!-- End of DTD -->
<!-- =============================================================== -->

=== DXYyang/SDP/sourcedata/poi-REL_3_0/src/documentation/content/xdocs/changes.xml
<?xml version="1.0"?>
<!--
   ====================================================================
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
   ====================================================================
-->
<!DOCTYPE changes PUBLIC "-//APACHE//DTD Changes V1.1//EN" "./dtd/changes-v11.dtd">

<changes>

    <title>History of Changes</title>

    <devs>
        <!-- in strict alphabetical order -->
        <person id="AO" name="Andrew C. Oliver" email="acoliver2@users.sourceforge.net"/>
        <person id="GJS" name="Glen Stampoultzis" email="poi-user@jakarta.apache.org"/>
        <person id="MJ" name="Marc Johnson" email="mjohnson@apache.org"/>
        <person id="NKB" name="Nicola Ken Barozzi" email="barozzi@nicolaken.com"/>
        <person id="NB" name="Nick Burch" email="nick@torchbox.com"/>
        <person id="POI-DEVELOPERS" name="POI Developers" email="poi-dev@jakarta.apache.org"/>
        <person id="RK" name="Rainer Klute" email="klute@apache.org"/>
        <person id="YK" name="Yegor Kozlov" email="yegor@apache.org"/>
    </devs>
        <release version="3.0-FINAL" date="99 May 2007">
            <action dev="POI-DEVELOPERS" type="fix">39977 - [PATCH] Fix POM for Maven users</action>
            <action dev="POI-DEVELOPERS" type="fix">38976 - [PATCH] Add createPicture to HSSFShapeGroup</action>
            <action dev="POI-DEVELOPERS" type="add">Detect Office 2007 XML documents, and throw a meaningful exception</action>
			<action dev="POI-DEVELOPERS" type="add">Additional HSLF support for PowerPoint</action>
			<action dev="POI-DEVELOPERS" type="add">Initial support for HWPF image extraction</action>
        </release>

        <release version="3.0-alpha3" date="12 December 2006">
			<action dev="POI-DEVELOPERS" type="add">Additional HSLF support for PowerPoint</action>
        </release>

        <release version="3.0-alpha2" date="16 June 2006">
            <action dev="POI-DEVELOPERS" type="add">HSSF Formula support</action>
			<action dev="POI-DEVELOPERS" type="add">Additional HSLF support for PowerPoint</action>
            <action dev="POI-DEVELOPERS" type="fix">39389 - [PATCH] Extended Ascii support for WingDings</action>
        </release>

        <release version="3.0-alpha1" date="4 July 2005">
            <action dev="POI-DEVELOPERS" type="fix">Bugzilla Bug 29976 [PATCH] HSSF hyperlink formula size problem</action>
            <action dev="POI-DEVELOPERS" type="add">Image writing support</action>
            <action dev="NB" type="add">HSLF - Initial PowerPoint support</action>
        </release>

        <release version="2.5.1-FINAL" date="29 Feburary 2004">
            <action dev="POI-DEVELOPERS" type="add">Outlining support</action>
            <action dev="POI-DEVELOPERS" type="fix">27574 - [PATCH] HSSFDateUtil.getExcelDate() is one hour off when DST changes</action>
            <action dev="POI-DEVELOPERS" type="fix">26465 - [PATCH] wrong lastrow entry</action>
            <action dev="POI-DEVELOPERS" type="fix">28203 - [PATCH] Unable to open read-write excel file including forms</action>
        </release>

        <release version="2.5-FINAL" date="29 Feburary 2004">
            <action dev="POI-DEVELOPERS" type="add">Add support for the Escher file format</action>
            <action dev="POI-DEVELOPERS" type="fix">27005 java.lang.IndexOutOfBoundsException during Workbook.cloneSheet()</action>
        </release>

        <release version="2.0-FINAL" date="26 Janurary 2004">
            <action dev="POI-DEVELOPERS" type="update">No changes</action>
        </release>

        <release version="2.0-RC2" date="11 Janurary 2004">
            <action dev="POI-DEVELOPERS" type="fix">Bug 25695 - HSSFCell.getStringCellValue() on cell which has string formula will return swap bye unicode characters.</action>
            <action dev="POI-DEVELOPERS" type="fix">Updated website for upcoming release</action>
            <action dev="POI-DEVELOPERS" type="fix">Formula Parser fixes with tests, by Peter M Murray Bug 25457</action>
            <action dev="POI-DEVELOPERS" type="fix">Fixed cloning merge regions</action>
            <action dev="POI-DEVELOPERS" type="fix">The cloned reference for merged cells did not create a new collection, so deletes cascaded to the original.</action>
            <action dev="POI-DEVELOPERS" type="fix">Fix to 24519 call to getCustomPalette() from a newly created workbook now works</action>
            <action dev="POI-DEVELOPERS" type="fix">Fix supplied for bug 24397 where some compilation got ambiguous classes.  Explicitly imports the classes.  Patch supplied by Jean-Pierre Paris.</action>
        </release>
        <release version="2.0-RC1" date="2 November 2003">
            <action dev="POI-DEVELOPERS" type="fix">12561 (Min)   HSSFWorkbook throws Exceptions</action>
            <action dev="POI-DEVELOPERS" type="fix">12730 (Nor)   values dont get copied to another sheet.</action>
            <action dev="POI-DEVELOPERS" type="fix">13224 (Maj)   Exception thrown when cell has =Names call</action>
            <action dev="POI-DEVELOPERS" type="fix">13796 (Nor)   Error Reading Formula Record (optimized if, external link)</action>
            <action dev="POI-DEVELOPERS" type="fix">13921 (Nor)   Sheet name cannot exceed 31 characters and cannot contain :</action>
            <action dev="POI-DEVELOPERS" type="fix">14330 (Nor)   Error reading FormulaRecord</action>
            <action dev="POI-DEVELOPERS" type="fix">14460 (Nor)   Name in Formula - ArrayOutOfBoundsException</action>
            <action dev="POI-DEVELOPERS" type="fix">15228 (Cri)   [Urgent] ArrayIndexoutofbounds Exception. POI - Version 1.8</action>
            <action dev="POI-DEVELOPERS" type="fix">16488 (Maj)   Unable to open written spreadsheet in Excel, but can in Open</action>
            <action dev="POI-DEVELOPERS" type="fix">16559 (Nor)   testCustomPalette.xls crashes Excel 97</action>
            <action dev="POI-DEVELOPERS" type="fix">16560 (Nor)   testBoolErr.xls crashes Excel '97</action>
            <action dev="POI-DEVELOPERS" type="fix">17374 (Min)   HSSFFont - BOLDWEIGHT_NORMAL</action>
            <action dev="POI-DEVELOPERS" type="fix">18800 (Maj)   The sheet made by HSSFWorkbook#cloneSheet() doesn't work cor</action>
            <action dev="POI-DEVELOPERS" type="fix">18846 (Min)   [PATCH][RFE]Refactor the transformation between byte array a</action>
            <action dev="POI-DEVELOPERS" type="fix">19599 (Min)   java.lang.IllegalArgumentException</action>
            <action dev="POI-DEVELOPERS" type="fix">19961 (Nor)   [PATCH] Sheet.getColumnWidth() returns wrong value</action>
            <action dev="POI-DEVELOPERS" type="fix">21066 (Blo)   Can not modify a blank spreadsheet</action>
            <action dev="POI-DEVELOPERS" type="fix">21444 (Enh)   [PATCH] Macro functions</action>
            <action dev="POI-DEVELOPERS" type="fix">21447 (Nor)   [RFE]String Formula Cells</action>
            <action dev="POI-DEVELOPERS" type="fix">21674 (Enh)   [PATCH] Documentation changes for @(Greater|Less|Not)EqualPt</action>
            <action dev="POI-DEVELOPERS" type="fix">21863 (Enh)   [PATCH] build.xml fixes</action>
            <action dev="POI-DEVELOPERS" type="fix">22195 (Nor)   [RFE] [PATCH] Support for Storage Class ID</action>
            <action dev="POI-DEVELOPERS" type="fix">22742 (Cri)   Failed to create HSSFWorkbook!</action>
            <action dev="POI-DEVELOPERS" type="fix">22922 (Cri)   HSSFSheet.shiftRows() throws java.lang.IndexOutOfBoundsExcep</action>
            <action dev="POI-DEVELOPERS" type="fix">22963 (Nor)   org.apache.poi.hpsf.SummaryInformation.getEditTime() should</action>
            <action dev="POI-DEVELOPERS" type="fix">24149 (Maj)   Error passing inputstream to POIFSFileSystem</action>
            <action dev="POI-DEVELOPERS" type="fix">21722 (Nor)   [PATCH] Add a ProtectRecord to Sheets and give control over</action>
            <action dev="POI-DEVELOPERS" type="fix">9576  (Nor)   [PATCH] DBCELL, INDEX EXTSST (was Acess 97 import)</action>
            <action dev="POI-DEVELOPERS" type="fix">13478 (Blo)   [PATCH] [RFE] POIFS, RawDataBlock: Missing workaround for lo</action>
            <action dev="POI-DEVELOPERS" type="fix">14824 (Nor)   Unable to modify empty sheets</action>
            <action dev="POI-DEVELOPERS" type="fix">12843 (Cri)   [PATCH] Make POI handle chinese better</action>
            <action dev="POI-DEVELOPERS" type="fix">15353 (Nor)   [RFE] creating a cell with a hyperlink</action>
            <action dev="POI-DEVELOPERS" type="fix">15375 (Blo)   Post 1.5.1 POI causes spreadsheet to become unopenable.</action>
        </release>

        <release version="2.0-pre3" date="29 July 2003">
